# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhwBfguN0cgmwuLH9LaYUO760xeKirxL
"""

import requests
import pandas as pd
import time
import os
from datetime import datetime

# Step 1: Configuration & Setup
BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}
# Step 2: Fetch Top Story IDs
print("Fetching first 500 story IDs")
top_ids = requests.get(f"{BASE_URL}/topstories.json", headers=HEADERS).json()[:500]

# Step 3: Fetch Details & Assign Categories
extracted_data = []

for cat_name, keywords in CATEGORIES.items():
    print(f"Collecting 25 stories for: {cat_name}")
    count = 0

    for story_id in top_ids:
 # Stop once we hit the category cap
        if count >= 25:
            break

        try:
            # Fetch specific story details
            story = requests.get(f"{BASE_URL}/item/{story_id}.json", headers=HEADERS).json()
            title = story.get("title", "")

            # Check if title matches any category keywords
            if any(word.lower() in title.lower() for word in keywords):
                extracted_data.append({
                    "post_id": story.get("id"),
                    "title": title,
                    "category": cat_name,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                })
                count += 1
        except:
            print(f"Failed to fetch ID {story_id}, moving on")
            continue

    # Respecting the 2-second delay per category requirement
    print(f"Finished {cat_name}. Sleeping")
    time.sleep(2)

# Step 4: Creating Directory & Export to JSON
if not os.path.exists('data'):
    os.makedirs('data')

# Dynamic filename with current date
date_str = datetime.now().strftime("%Y%m%d")
json_path = f"data/trends_{date_str}.json"

# Materialize data into DataFrame and save
trend_pulse_df = pd.DataFrame(extracted_data)
trend_pulse_df.to_json(json_path, orient="records", indent=4)

print(f"\nTotal stories collected: {len(trend_pulse_df)}")
print(f"JSON file generated: {json_path}")