# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qw46eJt0H7ndR_YYLuQx4eT8vbVPifXv
"""

import requests
import time

# Setting up global variables for the API and headers as per requirements
BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

# Keywords grouped by category for the matching logic when needed
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}
def fetch_top_stories():
    """
    Step 1: Get the list of IDs.
    We fetch the top 500 stories as requested in the task brief.
    """
    try:
        response = requests.get(f"{BASE_URL}/topstories.json", headers=HEADERS)
        response.raise_for_status()
        # Slicing the list to only get the first 500 items
        return response.json()[:500]
    except Exception as e:
        # Error handling to prevent the script from crashing if the API is down
        print(f"Request failed: {e}")
        return []
def fetch_story_details(story_id):
    """
    Step 2: Get specific details for a story ID.
    This fetches the JSON object containing the title and URL.
    """
    try:
        url = f"{BASE_URL}/item/{story_id}.json"
        response = requests.get(url, headers=HEADERS)
        return response.json()
    except Exception as e:
        print(f"Could not fetch details for ID {story_id}: {e}")
        return None
def main():
    # Start the collection process
    print("Starting data collection")
    top_ids = fetch_top_stories()

    if not top_ids:
        return
    categorized_data = []

    # Processing by category as requested in the 'Wait 2 seconds' requirement
    for category_name, keywords in CATEGORIES.items():
        print(f"Filtering for: {category_name}")

        for story_id in top_ids:
            story = fetch_story_details(story_id)

            # Logic: Check if the title exists and contains any of our keywords
            if story and "title" in story:
                title_lower = story["title"].lower()

                # Check each keyword against the story title
                for word in keywords:
                    if word.lower() in title_lower:
                        # If a match is found, label it and save it
                        story["assigned_category"] = category_name
                        categorized_data.append(story)
                        break # Stop checking other keywords for this story once matched

        # Wait 2 seconds after completing one full category loop
        print(f"Finished {category_name} loop. Sleeping")
        time.sleep(2)

    print(f"Successfully collected {len(categorized_data)} stories.")

if __name__ == "__main__":
    main()
