# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqm_0OZ0-VMWOQhAZ8hpscOFSJuAAnah
"""

import requests
import pandas as pd
import time
import os
import matplotlib.pyplot as plt
from datetime import datetime

# Step 1: Configuration
BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

# Step 2: Data Collection
print("Fetching top 500 stories")
top_ids = requests.get(f"{BASE_URL}/topstories.json", headers=HEADERS).json()[:500]

extracted_stories = []

for category, keywords in CATEGORIES.items():
    print(f"Finding 25 stories for: {category}")
    found_in_cat = 0

    for sid in top_ids:
        if found_in_cat >= 25: break
        # Cap reached

        try:
            story = requests.get(f"{BASE_URL}/item/{sid}.json", headers=HEADERS).json()
            title = story.get("title", "")

            # Match keywords and extract required fields
            if any(k.lower() in title.lower() for k in keywords):
                extracted_stories.append({
                    "post_id": story.get("id"),
                    "title": title,
                    "category": category,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                })
                found_in_cat += 1
        except:
            continue

    print(f"Finished {category}. Sleeping")
    time.sleep(2)

# Step 3: Storing
# Create data folder if missing
if not os.path.exists('data'):
    os.makedirs('data')

# Format filename: data/trends_YYYYMMDD.json
file_path = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

# Materialize to DataFrame for export
trend_pulse = pd.DataFrame(extracted_stories)
trend_pulse.to_json(file_path, orient="records", indent=4)

# Step 4: Visualizing the output
print("\nGenerating Visual Summary")

# Plotting the count of stories per category
category_counts = trend_pulse['category'].value_counts()

plt.figure(figsize=(10, 6))
category_counts.plot(kind='bar', color='teal', edgecolor='black')

plt.title('TrendPulse: Stories Collected per Category', fontsize=14)
plt.xlabel('Category', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()
print("\n" + "="*30)
print(f"Total stories collected: {len(trend_pulse)}")
print(f"Data saved to: {file_path}")
print("="*30)