# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaH-pc9FTraLGXeqUhqm0I2QoXOqwU69
"""

import requests
import pandas as pd
import time
from datetime import datetime

# Configuration
BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

# Step 1: Fetch IDs
print("Fetching top stories")
top_ids = requests.get(f"{BASE_URL}/topstories.json", headers=HEADERS).json()[:500]

# Step 2: Extract Fields & Filter
all_stories = []

for category_name, keywords in CATEGORIES.items():
    print(f"Collecting 25 stories for: {category_name}")
    count = 0

    for story_id in top_ids:
        if count >= 25: # Cap at 25 per category
            break

        try:
            # Fetch individual story details
            story = requests.get(f"{BASE_URL}/item/{story_id}.json", headers=HEADERS).json()
            title = story.get("title", "").lower()

            # Check if any keyword matches the title
            if any(word.lower() in title for word in keywords):
                # Mapping the 7 required fields from the task
                story_data = {
                    "post_id": story.get("id"),
                    "title": story.get("title"),
                    "category": category_name,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }
                all_stories.append(story_data)
                count += 1
        except:
            print(f"Skipping ID {story_id}")
            continue

    # Wait 2 seconds after each category loop finishes
    print(f"Finished {category_name}. Sleeping 2 seconds")
    time.sleep(2)

# Step 3: Materialize to DataFrame & Export
# Using your idiomatic format: transforming the list into the final table
trend_pulse_df = pd.DataFrame(all_stories)

print("\nFinal Collection Summary")
print(trend_pulse_df.groupby('category').size())

print("\nData Preview")
print(trend_pulse_df.head())

# Saving the output for the next task
trend_pulse_df.to_csv("task1_data_collection.csv", index=False)